### ISSUE TITLE
error

### ISSUE THREAD

**Issue by golimer** [gitinsky/ansible-role-radiusdesk#1]
ERROR! the role 'nodejs' was not found in /Users/gedas/projects/ansible/roles:/Users/gedas/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/gedas/projects/ansible/roles:/Users/gedas/projects/ansible

The error appears to have been in '/Users/gedas/projects/ansible/roles/ansible-role-radiusdesk/meta/main.yml': line 3, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

dependencies:
  - { role: nodejs }

**Comment by hryamzik** [comment]
```
git clone https://github.com/gitinsky/ansible-role-nodejs roles/nodejs
```
